version: 2

updates:
  # Swift Package Manager dependencies for AxiomFramework
  - package-ecosystem: "swift"
    directory: "/AxiomFramework"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "axiom-maintainers"
    assignees:
      - "axiom-maintainers"
    commit-message:
      prefix: "deps(swift)"
      include: "scope"
    labels:
      - "dependencies"
      - "swift-package-manager"
      - "framework"
    
  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    reviewers:
      - "axiom-maintainers"
    assignees:
      - "axiom-maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
      
  # Xcode project dependencies (if using CocoaPods or similar)
  - package-ecosystem: "cocoapods"
    directory: "/AxiomExampleApp"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    reviewers:
      - "axiom-maintainers"
    assignees:
      - "axiom-maintainers"
    commit-message:
      prefix: "deps(ios)"
      include: "scope"
    labels:
      - "dependencies"
      - "cocoapods"
      - "example-app"
    # Only create PRs if there are no existing dependency PRs
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"