# SwiftLint configuration for Axiom Framework API naming consistency

# Custom rules to enforce API naming conventions
custom_rules:
  redundant_protocol_suffix:
    name: "Redundant Protocol Suffix"
    regex: "protocol\\s+\\w+Protocol\\s*[:{]"
    message: "Don't use 'Protocol' suffix in protocol names"
    severity: error
    
  inconsistent_async_naming:
    name: "Inconsistent Async Naming"
    regex: "(fetchDataAsync|loadAsync|Async\\()"
    message: "Don't use 'Async' suffix for async methods"
    severity: error
    
  vague_base_prefix:
    name: "Vague Base Prefix"
    regex: "class\\s+Base\\w+"
    message: "Avoid 'Base' prefix; use specific names like 'Standard' or 'Default'"
    severity: warning
    
  boolean_without_prefix:
    name: "Boolean Without Prefix"
    regex: "var\\s+(?!is|has|can|should|will)\\w+:\\s*Bool"
    message: "Boolean properties should start with is/has/can/should/will"
    severity: error
    
  lifecycle_method_naming:
    name: "Lifecycle Method Naming"
    regex: "(func\\s+(on|perform)[A-Z]\\w*\\(|func\\s+handle[A-Z]\\w*\\()"
    message: "Use consistent verb tense for lifecycle methods (past tense for events)"
    severity: warning
    
  interface_suffix:
    name: "Redundant Interface Suffix"
    regex: "protocol\\s+\\w+Interface\\s*[:{]"
    message: "Don't use 'Interface' suffix in protocol names"
    severity: error

# Standard SwiftLint rules
included:
  - Sources
  - Tests

excluded:
  - .build
  - Package.swift

# Rule configuration
identifier_name:
  min_length: 2
  max_length: 60

type_name:
  min_length: 3
  max_length: 50

function_parameter_count:
  warning: 6
  error: 8

line_length:
  warning: 120
  error: 150
  ignores_comments: true

# Opt-in rules for better API design
opt_in_rules:
  - explicit_init
  - first_where
  - missing_docs
  - sorted_imports
  - unneeded_parentheses_in_closure_argument