[server]
name = "axiom-aspire-deployer"
version = "1.0.0"
port = 3001
host = "127.0.0.1"

[aspire]
# Auto-detect running Aspire instances
auto_discovery = true
# Default dashboard URL to check
dashboard_url = "https://localhost:15888"
# Polling interval for service status
polling_interval_ms = 1000
# Timeout for API calls
api_timeout_ms = 5000

[monitoring]
# Enable process monitoring
monitor_processes = true
# Enable file system watching for config changes
watch_config_files = true
# Services to monitor health endpoints
health_check_interval_ms = 5000

[network]
# Network interface for service discovery
local_interface = "0.0.0.0"
# Enable network scanning for services
network_scan_enabled = true
# Port range to scan for services
port_scan_range = "7000-8000"

[logging]
level = "info"
# Log file location
file = "axiom-aspire-mcp.log"
# Enable structured logging
structured = true